language: node_js
node_js:
  - "7"
  - "6"
  - "4"
os:
  - linux
  - osx
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      env: TEST=test

    - os: linux
      dist: trusty
      sudo: false
      env: TEST=e2e-test _FORCE_LOGS=1

    - os: osx
      osx_image: xcode9
      env: TEST=test

    - os: osx
      osx_image: xcode9
      env: TEST=e2e-test _FORCE_LOGS=1
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm run lint && npm run $TEST
after_success:
  - npm run coveralls
